GMAIL_USERNAME: "huyhoc1310"
GMAIL_PASSWORD: "Huyhoc861100"
GOOGLE_OAUTH2_APP_ID: "513958491289-5h2nsbp7p382f542oi1s032a5eeu2077.apps.googleusercontent.com"
GOOGLE_OAUTH2_APP_SECRET: "vqufvZZl9ot2RjoGw2xysV9K"
